import type { Artisan, Review, Category } from './types';
import { Hammer, Brush, Scissors, Wrench, Utensils, Shirt } from 'lucide-react';

export const categories: Category[] = [
    { name: 'Carpenters', icon: Hammer },
    { name: 'Painters', icon: Brush },
    { name: 'Tailors', icon: Scissors },
    { name: 'Plumbers', icon: Wrench },
    { name: 'Chefs', icon: Utensils },
    { name: 'Designers', icon: Shirt },
];

export const reviewsData: Review[] = [
  {
    id: 'review1',
    author: 'Jane Doe',
    avatarUrl: 'https://placehold.co/100x100.png',
    rating: 5,
    comment: 'Absolutely phenomenal work! The attention to detail was impeccable. Highly recommend for any custom furniture needs.',
    date: '2023-05-15',
  },
  {
    id: 'review2',
    author: 'John Smith',
    avatarUrl: 'https://placehold.co/100x100.png',
    rating: 4,
    comment: 'Very professional and completed the job on time. The new shelves look great. There was a minor scuff but they fixed it immediately.',
    date: '2023-04-22',
  },
   {
    id: 'review3',
    author: 'Emily White',
    avatarUrl: 'https://placehold.co/100x100.png',
    rating: 5,
    comment: 'The room looks fantastic! Very clean work and friendly service.',
    date: '2023-06-01',
  },
];


export const artisanData: Artisan[] = [
  {
    id: '1',
    name: 'Elena Garcia',
    email: 'elena.garcia@example.com',
    phone: '(555) 123-4567',
    category: 'Carpenter',
    location: 'Brooklyn, NY',
    rating: 4.9,
    reviewsCount: 128,
    imageUrl: 'https://placehold.co/600x400.png',
    'data-ai-hint': 'woman carpenter',
    skills: ['Custom Furniture', 'Cabinetry', 'Wood-turning', 'Restoration'],
    experience: '15+ years',
    bio: 'Elena is a master carpenter with a passion for sustainable materials and timeless design. Her workshop in Brooklyn is a hub of creativity, where she brings clients\' visions to life, from intricate cabinetry to bespoke dining tables.',
    services: ['Custom dining tables', 'Kitchen cabinet making', 'Bookshelf construction', 'Antique furniture restoration'],
    reviews: reviewsData,
  },
  {
    id: '2',
    name: 'Marcus Holloway',
    email: 'marcus.holloway@example.com',
    phone: '(555) 234-5678',
    category: 'Painter',
    location: 'San Francisco, CA',
    rating: 4.8,
    reviewsCount: 92,
    imageUrl: 'https://placehold.co/600x400.png',
    'data-ai-hint': 'man painter',
    skills: ['Interior Painting', 'Exterior Painting', 'Mural Art', 'Faux Finishes'],
    experience: '10 years',
    bio: 'Marcus combines precision with an artistic eye to transform spaces with color. He specializes in both residential and commercial projects, known for his clean lines and efficient work.',
    services: ['Full interior home painting', 'Exterior facade painting', 'Custom accent walls', 'Commercial office painting'],
    reviews: [reviewsData[2]],
  },
  {
    id: '3',
    name: 'Aisha Khan',
    email: 'aisha.khan@example.com',
    phone: '(555) 345-6789',
    category: 'Tailor',
    location: 'Chicago, IL',
    rating: 5.0,
    reviewsCount: 210,
    imageUrl: 'https://placehold.co/600x400.png',
    'data-ai-hint': 'woman tailor',
    skills: ['Bespoke Suits', 'Dressmaking', 'Alterations', 'Pattern Making'],
    experience: '20 years',
    bio: 'With two decades of experience, Aisha is a renowned tailor specializing in bespoke garments. Her attention to fit and fabric is second to none, creating pieces that are both beautiful and comfortable.',
    services: ['Custom suit fitting and creation', 'Wedding dress alterations', 'Vintage clothing resizing', 'General clothing repairs'],
    reviews: [],
  },
  {
    id: '4',
    name: 'David Chen',
    email: 'david.chen@example.com',
    phone: '(555) 456-7890',
    category: 'Plumber',
    location: 'Austin, TX',
    rating: 4.7,
    reviewsCount: 154,
    imageUrl: 'https://placehold.co/600x400.png',
    'data-ai-hint': 'man plumber',
    skills: ['Pipe Repair', 'Drain Cleaning', 'Fixture Installation', 'Water Heaters'],
    experience: '12 years',
    bio: 'David is a licensed and insured plumber providing reliable and friendly service. He is known for his quick response times and effective solutions to all plumbing problems, big or small.',
    services: ['Emergency leak repair', 'Clogged drain service', 'Toilet and sink installation', 'Water heater maintenance'],
    reviews: [],
  },
  // Add more artisans to make the search page more realistic
  {
    id: '5',
    name: 'Isabella Rossi',
    email: 'isabella.rossi@example.com',
    phone: '(555) 567-8901',
    category: 'Chef',
    location: 'Miami, FL',
    rating: 4.9,
    reviewsCount: 88,
    imageUrl: 'https://placehold.co/600x400.png',
    'data-ai-hint': 'woman chef',
    skills: ['Italian Cuisine', 'Pastry', 'Event Catering', 'Menu Design'],
    experience: '18 years',
    bio: 'Classically trained in Florence, Isabella brings authentic Italian flavor to private events. She uses locally-sourced ingredients to create unforgettable culinary experiences.',
    services: ['Private dinner parties', 'Wedding catering', 'Cooking classes', 'Custom menu development'],
    reviews: [],
  },
  {
    id: '6',
    name: 'Leo Maxwell',
    email: 'leo.maxwell@example.com',
    phone: '(555) 678-9012',
    category: 'Designer',
    location: 'Los Angeles, CA',
    rating: 4.8,
    reviewsCount: 75,
    imageUrl: 'https://placehold.co/600x400.png',
    'data-ai-hint': 'man designer',
    skills: ['Graphic Design', 'Brand Identity', 'Web Design', 'Illustration'],
    experience: '8 years',
    bio: 'Leo is a modern graphic designer who helps brands tell their story visually. His aesthetic is clean, bold, and impactful, delivering results that resonate with audiences.',
    services: ['Logo and branding packages', 'Website design (UI/UX)', 'Marketing material creation', 'Custom illustrations'],
    reviews: [],
  },
];
